version: 2

models:

  - name: stg_artists
    description: Clean Spotify artist records.

    columns:

      - name: artist_id
        tests:
          - unique
          - not_null

      - name: artist_name
        tests:
          - not_null

      - name: followers
        tests:
          - not_null

      - name: popularity
        tests:
          - not_null


  - name: stg_albums
    description: Clean Spotify album records.

    columns:

      - name: album_id
        tests:
          - unique
          - not_null

      - name: artist_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_artists')
                field: artist_id

      - name: album_name
        tests:
          - not_null

      - name: release_date
        tests:
          - not_null


  - name: stg_tracks
    description: Clean Spotify track records.

    columns:

      - name: track_id
        tests:
          - unique
          - not_null

      - name: album_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_albums')
                field: album_id

      - name: track_name
        tests:
          - not_null

      - name: duration_mins
        tests:
          - not_null

      - name: track_number
        tests:
          - not_null
      - name: explicit
        tests:
          - accepted_values:
              arguments:
                values: [true, false]

  - name: fact_album_metrics
    description: Fact table for album metrics.

    columns:

      - name: album_id
        tests:
          - not_null
          - unique

      - name: track_count
        tests:
          - not_null

      - name: avg_track_duration
        tests:
          - not_null

  - name: fact_artist_metrics
    description: Fact table for artist metrics.

    columns:

      - name: artist_id
        tests:
          - not_null
          - unique

      - name: album_count
        tests:
          - not_null